### ISSUE TITLE
Fitbit sleep parsing fails when there is no data

### ISSUE THREAD

**Issue by JulioV** [carissalow/rapids#28]
```
[Mon Jan 27 11:08:13 2020]
rule fitbit_with_datetime:
    input: data/raw/p26/fitbit_data_raw.csv
    output: data/raw/p26/fitbit_sleep_with_datetime.csv
    jobid: 2763
    wildcards: pid=p26, fitbit_sensor=sleep
Traceback (most recent call last):
  File "/Users/juliovega/Documents/rythms/moshi-aware-rythms/.snakemake/scripts/tmpj5lck647.fitbit_readable_datetime.py", line 150, in <module>
    data_preprocesed = parse_sleep_data(data)
  File "/Users/juliovega/Documents/rythms/moshi-aware-rythms/.snakemake/scripts/tmpj5lck647.fitbit_readable_datetime.py", line 78, in parse_sleep_data
    device_id = sleep_data["device_id"].iloc[0]
  File "/usr/local/Caskroom/miniconda/base/envs/rythms-env/lib/python3.7/site-packages/pandas/core/indexing.py", line 1424, in __getitem__
    return self._getitem_axis(maybe_callable, axis=axis)
  File "/usr/local/Caskroom/miniconda/base/envs/rythms-env/lib/python3.7/site-packages/pandas/core/indexing.py", line 2157, in _getitem_axis
    self._validate_integer(key, axis)
  File "/usr/local/Caskroom/miniconda/base/envs/rythms-env/lib/python3.7/site-packages/pandas/core/indexing.py", line 2088, in _validate_integer
    raise IndexError("single positional indexer is out-of-bounds")
IndexError: single positional indexer is out-of-bounds
```

**Comment by Meng6** [comment]
Add an if statement before parsing the steps/heartrate/sleep data.
